//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Feedbacks {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Feedbacks() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Feedbacks", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Plans is required(Max 1000 char.).
        /// </summary>
        internal static string Error_ActionPlans {
            get {
                return ResourceManager.GetString("Error_ActionPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch is required..
        /// </summary>
        internal static string Error_Branch {
            get {
                return ResourceManager.GetString("Error_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit is required..
        /// </summary>
        internal static string Error_BusinessUnits {
            get {
                return ResourceManager.GetString("Error_BusinessUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment is required..
        /// </summary>
        internal static string Error_CCFileNameList {
            get {
                return ResourceManager.GetString("Error_CCFileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment is required..
        /// </summary>
        internal static string Error_CCQAInchargeFileNameList {
            get {
                return ResourceManager.GetString("Error_CCQAInchargeFileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Quality Incharge User is required..
        /// </summary>
        internal static string Error_CCQualityInchargeUser {
            get {
                return ResourceManager.GetString("Error_CCQualityInchargeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Incharge User Comments is required.
        /// </summary>
        internal static string Error_CCQualityInchargeUserComments {
            get {
                return ResourceManager.GetString("Error_CCQualityInchargeUserComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Description is required (Max 1000  char.).
        /// </summary>
        internal static string Error_DefectDescription {
            get {
                return ResourceManager.GetString("Error_DefectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Title is required (Max 255 Char.).
        /// </summary>
        internal static string Error_FeedbackTitle {
            get {
                return ResourceManager.GetString("Error_FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment is required..
        /// </summary>
        internal static string Error_FileNameList {
            get {
                return ResourceManager.GetString("Error_FileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward to CC Quality Incharge is required.
        /// </summary>
        internal static string Error_ForwardtoCCQualityIncharge {
            get {
                return ResourceManager.GetString("Error_ForwardtoCCQualityIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward to Quality is required..
        /// </summary>
        internal static string Error_ForwardtoQuality {
            get {
                return ResourceManager.GetString("Error_ForwardtoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code is required.
        /// </summary>
        internal static string Error_ItemCode {
            get {
                return ResourceManager.GetString("Error_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description is required..
        /// </summary>
        internal static string Error_ItemDescription {
            get {
                return ResourceManager.GetString("Error_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name is required (Max 255 char.).
        /// </summary>
        internal static string Error_ModelName {
            get {
                return ResourceManager.GetString("Error_ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations is required(Max 1000 char.).
        /// </summary>
        internal static string Error_Observations {
            get {
                return ResourceManager.GetString("Error_Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Cause/ issue related to required..
        /// </summary>
        internal static string Error_ProblemCause {
            get {
                return ResourceManager.GetString("Error_ProblemCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Serial is required (Max 1000  char.).
        /// </summary>
        internal static string Error_ProductSerial {
            get {
                return ResourceManager.GetString("Error_ProductSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group is required.
        /// </summary>
        internal static string Error_ProductType {
            get {
                return ResourceManager.GetString("Error_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality User is required..
        /// </summary>
        internal static string Error_QAUser {
            get {
                return ResourceManager.GetString("Error_QAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Code is required (4 digit only)..
        /// </summary>
        internal static string Error_SupplierCode {
            get {
                return ResourceManager.GetString("Error_SupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Date.
        /// </summary>
        internal static string Grid_Title_AssignDate {
            get {
                return ResourceManager.GetString("Grid_Title_AssignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string Grid_Title_Branch {
            get {
                return ResourceManager.GetString("Grid_Title_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        internal static string Grid_Title_BusinessUnit {
            get {
                return ResourceManager.GetString("Grid_Title_BusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCActing User.
        /// </summary>
        internal static string Grid_Title_CCActingUser {
            get {
                return ResourceManager.GetString("Grid_Title_CCActingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCQuality Incharge User.
        /// </summary>
        internal static string Grid_Title_CCQualityInchargeUser {
            get {
                return ResourceManager.GetString("Grid_Title_CCQualityInchargeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Grid_Title_Comment {
            get {
                return ResourceManager.GetString("Grid_Title_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        internal static string Grid_Title_CreationDate {
            get {
                return ResourceManager.GetString("Grid_Title_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Description.
        /// </summary>
        internal static string Grid_Title_DefectDescription {
            get {
                return ResourceManager.GetString("Grid_Title_DefectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback No.
        /// </summary>
        internal static string Grid_Title_FeedbackNo {
            get {
                return ResourceManager.GetString("Grid_Title_FeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Title.
        /// </summary>
        internal static string Grid_Title_FeedbackTitle {
            get {
                return ResourceManager.GetString("Grid_Title_FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string Grid_Title_ItemCode {
            get {
                return ResourceManager.GetString("Grid_Title_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Cause.
        /// </summary>
        internal static string Grid_Title_ProblemCause {
            get {
                return ResourceManager.GetString("Grid_Title_ProblemCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        internal static string Grid_Title_ProductGroup {
            get {
                return ResourceManager.GetString("Grid_Title_ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Serial.
        /// </summary>
        internal static string Grid_Title_ProductSerial {
            get {
                return ResourceManager.GetString("Grid_Title_ProductSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed By.
        /// </summary>
        internal static string Grid_Title_ProposedBy {
            get {
                return ResourceManager.GetString("Grid_Title_ProposedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Grid_Title_Status {
            get {
                return ResourceManager.GetString("Grid_Title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Plans:.
        /// </summary>
        internal static string Label_ActionPlans {
            get {
                return ResourceManager.GetString("Label_ActionPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch:.
        /// </summary>
        internal static string Label_Branch {
            get {
                return ResourceManager.GetString("Label_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit:.
        /// </summary>
        internal static string Label_BusinessUnits {
            get {
                return ResourceManager.GetString("Label_BusinessUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Acting User.
        /// </summary>
        internal static string Label_CCActingUser {
            get {
                return ResourceManager.GetString("Label_CCActingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string Label_CCFileNameList {
            get {
                return ResourceManager.GetString("Label_CCFileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string Label_CCQAInchargeFileNameList {
            get {
                return ResourceManager.GetString("Label_CCQAInchargeFileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Quality Incharge.
        /// </summary>
        internal static string Label_CCQualityInchargeUser {
            get {
                return ResourceManager.GetString("Label_CCQualityInchargeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments/Remarks:.
        /// </summary>
        internal static string Label_Comment {
            get {
                return ResourceManager.GetString("Label_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Description:.
        /// </summary>
        internal static string Label_DefectDescription {
            get {
                return ResourceManager.GetString("Label_DefectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback No:.
        /// </summary>
        internal static string Label_FeedbackNo {
            get {
                return ResourceManager.GetString("Label_FeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Title:.
        /// </summary>
        internal static string Label_FeedbackTitle {
            get {
                return ResourceManager.GetString("Label_FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments:.
        /// </summary>
        internal static string Label_FileNameList {
            get {
                return ResourceManager.GetString("Label_FileNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward to CC Quality Incharge:.
        /// </summary>
        internal static string Label_ForwardtoCCQualityIncharge {
            get {
                return ResourceManager.GetString("Label_ForwardtoCCQualityIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward to Quality:.
        /// </summary>
        internal static string Label_ForwardtoQuality {
            get {
                return ResourceManager.GetString("Label_ForwardtoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward to Quality.
        /// </summary>
        internal static string Label_ForwardtoQuality1 {
            get {
                return ResourceManager.GetString("Label_ForwardtoQuality1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the issue.
        /// </summary>
        internal static string Label_ForwardtoQuality2 {
            get {
                return ResourceManager.GetString("Label_ForwardtoQuality2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward to CC Quality Incharge:.
        /// </summary>
        internal static string Label_ForwardtoQualityIncharge {
            get {
                return ResourceManager.GetString("Label_ForwardtoQualityIncharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward to CC Quality Incharge.
        /// </summary>
        internal static string Label_ForwardtoQualityIncharge1 {
            get {
                return ResourceManager.GetString("Label_ForwardtoQualityIncharge1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the issue.
        /// </summary>
        internal static string Label_ForwardtoQualityIncharge2 {
            get {
                return ResourceManager.GetString("Label_ForwardtoQualityIncharge2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code:.
        /// </summary>
        internal static string Label_ItemCode {
            get {
                return ResourceManager.GetString("Label_ItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Description:.
        /// </summary>
        internal static string Label_ItemDescription {
            get {
                return ResourceManager.GetString("Label_ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality User:.
        /// </summary>
        internal static string Label_LUMQAUser {
            get {
                return ResourceManager.GetString("Label_LUMQAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Name:.
        /// </summary>
        internal static string Label_ModelName {
            get {
                return ResourceManager.GetString("Label_ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations:.
        /// </summary>
        internal static string Label_Observations {
            get {
                return ResourceManager.GetString("Label_Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem Cause/ issue related to:.
        /// </summary>
        internal static string Label_ProblemCause {
            get {
                return ResourceManager.GetString("Label_ProblemCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Serial:.
        /// </summary>
        internal static string Label_ProductSerial {
            get {
                return ResourceManager.GetString("Label_ProductSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group:.
        /// </summary>
        internal static string Label_ProductType {
            get {
                return ResourceManager.GetString("Label_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed By:.
        /// </summary>
        internal static string Label_ProposedBy {
            get {
                return ResourceManager.GetString("Label_ProposedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality User:.
        /// </summary>
        internal static string Label_QAUser {
            get {
                return ResourceManager.GetString("Label_QAUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality User .
        /// </summary>
        internal static string Label_QualityUserCreator {
            get {
                return ResourceManager.GetString("Label_QualityUserCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date:.
        /// </summary>
        internal static string Label_RequestDate {
            get {
                return ResourceManager.GetString("Label_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Code:.
        /// </summary>
        internal static string Label_SupplierCode {
            get {
                return ResourceManager.GetString("Label_SupplierCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow Status.
        /// </summary>
        internal static string Label_WorkflowStatus {
            get {
                return ResourceManager.GetString("Label_WorkflowStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Acting User Section.
        /// </summary>
        internal static string Section_Title_CCActingUserSection {
            get {
                return ResourceManager.GetString("Section_Title_CCActingUserSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Quality Incharge Section.
        /// </summary>
        internal static string Section_Title_CCQualityInchargeSection {
            get {
                return ResourceManager.GetString("Section_Title_CCQualityInchargeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Quality Feedback Detail Section.
        /// </summary>
        internal static string Section_Title_FeedbackDetailDocumentSection {
            get {
                return ResourceManager.GetString("Section_Title_FeedbackDetailDocumentSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality User Section.
        /// </summary>
        internal static string Section_Title_QAUserSection {
            get {
                return ResourceManager.GetString("Section_Title_QAUserSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback is submitted successfully.
        /// </summary>
        internal static string Text_ApproveSuccess {
            get {
                return ResourceManager.GetString("Text_ApproveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback is closed successfully.
        /// </summary>
        internal static string Text_CompletedSuccess {
            get {
                return ResourceManager.GetString("Text_CompletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Report.
        /// </summary>
        internal static string Text_FeedbackReportTitle {
            get {
                return ResourceManager.GetString("Text_FeedbackReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback save as draft successfully.
        /// </summary>
        internal static string Text_SaveDraftSuccess {
            get {
                return ResourceManager.GetString("Text_SaveDraftSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback  saved successfully.
        /// </summary>
        internal static string Text_SaveSuccess {
            get {
                return ResourceManager.GetString("Text_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback is submitted successfully.
        /// </summary>
        internal static string Text_Success {
            get {
                return ResourceManager.GetString("Text_Success", resourceCulture);
            }
        }
    }
}
